site_name: Anonify
docs_dir: src
site_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - index.md
  - 動作方法:
    - Set up: Getting_Started/setup.md
    - Testing: Getting_Started/testing.md
  - チュートリアル:
    - ERC20:
      - CLI: Tutorials/ERC20/cli.md
      - Transfer/Approve: Tutorials/ERC20/transfer_approve.md
      - Mint/Burn: Tutorials/ERC20/mint_burn.md
  - 技術コンセプト:
    - 要素技術: Concepts/technologies.md
    - アーキテクチャ: Concepts/overview.md
    - プロパティ: Concepts/requirements.md
    - ワークフロー: Concepts/workflow.md

plugins:
  - search