site_name: Anonify
docs_dir: src
site_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  # logo: assets/images/logo5.svg
repo_name: Anonify
repo_url: https://github.com/LayerXcom/anonify
nav:
  - index.md
  - 動作方法:
    - セットアップ: Getting_Started/setup.md
    - テスト: Getting_Started/testing.md
    - サーバー起動: Getting_Started/start_server.md
    - ネットワークへ参加: Getting_Started/join.md
  - チュートリアル:
    - ERC20:
      - mint/burn: Tutorials/ERC20/mint_burn.md
      - transfer: Tutorials/ERC20/transfer.md
      - approve/transfer_from: Tutorials/ERC20/approve.md
  - 技術コンセプト:
    - 要素技術: Concepts/technologies.md
    - アーキテクチャ: Concepts/overview.md
    - プロパティ: Concepts/requirements.md
    - ワークフロー: Concepts/workflow.md

plugins:
  - search